name: EGM722_assignment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.8
  - geopandas
  - cartopy=0.18.0
  - notebook
  - rasterio
  - numpy
  - pandas
  - matplotlib
  - shapely
  - pysimplegui
  - pip
  - pip:
    - bng
    - matplotlib-scalebar
