name: assignment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.8
  - geopandas=0.9.0
  - cartopy=0.18.0
  - notebook=6.2.0
  - rasterio=1.2.0
  - numpy=1.22.3
  - pandas=1.4.1
  - matplotlib=3.5.1
  - shapely=1.8.0
  - pysimplegui=4.59.0
  - pip:
    - bng=1.0.5
    - matplotlib-scalebar=0.8.1
